# Deployment file 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: i27-user-dev
#  namespace: cart-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
        app: i27-user-dev
  template:
    metadata:
      labels:
        app: i27-user-dev
    spec:
      containers:
      - name: i27-user-dev
        image: DIT # this image along with tag will be replaced dynamically from shared lib
--- 
apiVersion: v1
kind: Service 
metadata:
  name: i27-user-dev
  labels:
    app: i27-user-dev
spec:
  type: NodePort
  ports:
  - port: 8232 # this is port on which service is running
    targetPort: 8232 # port where container is running
  selector:
    app: i27-user-dev