apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-user-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: i27-user-prod
  template: 
    metadata:
      labels:
        name: i27-user-prod
    spec: 
      imagePullSecrets: 
      - name: docker-secret  #same name you created "docker-registry secret" under stage namespace
      containers:
      - name: i27-user-prod
        image: DIT  # Docker image tag will replaces by shared libraries

---
apiVersion: v1 
kind: Service
metadata:
  name: i27-user-prod-svc
spec:
  selector:
    name: i27-user-prod #this name matches with the above matadata->labelname, otherwise it won't create the endpoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP    

---
# creating a ingress for your domain (domainname= cart.rakesh.stage.com)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-stage-ingress
  namespace: default
spec:
  rules:
    - host: cart.rakesh.stage.com  # ip's changing so we created domain name and using that domain name here and paste this name for application.yaml
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: i27-user-stage-svc  # Correct service name
                port:
                  number: 80          